-- ============================================================
-- SALES ANALYSIS SQL PROJECT
-- Database: sales_analysis
-- ============================================================


-- 1. TOTAL REVENUE
-- Revenue from completed orders only

SELECT
    SUM(oi.quantity * oi.unit_price) AS total_revenue
FROM orders AS o
JOIN order_items AS oi
    ON o.order_id = oi.order_id
WHERE o.order_status = 'Completed';


-- 2. MONTHLY REVENUE
-- Completed-order revenue by month

SELECT
    MONTH(o.order_date) AS sales_month,
    SUM(oi.quantity * oi.unit_price) AS monthly_revenue
FROM orders AS o
JOIN order_items AS oi
    ON o.order_id = oi.order_id
WHERE o.order_status = 'Completed'
GROUP BY MONTH(o.order_date)
ORDER BY sales_month;


-- 3. REVENUE BY PRODUCT
-- Products ranked by revenue

SELECT
    p.product_name,
    SUM(oi.quantity * oi.unit_price) AS total_revenue
FROM products AS p
JOIN order_items AS oi
    ON p.product_id = oi.product_id
JOIN orders AS o
    ON oi.order_id = o.order_id
WHERE o.order_status = 'Completed'
GROUP BY p.product_name
ORDER BY total_revenue DESC;


-- 4. REVENUE BY SALES EMPLOYEE
-- Revenue generated by each salesperson

SELECT
    e.employee_name,
    SUM(oi.quantity * oi.unit_price) AS total_revenue
FROM employees AS e
JOIN orders AS o
    ON e.employee_id = o.employee_id
JOIN order_items AS oi
    ON o.order_id = oi.order_id
WHERE o.order_status = 'Completed'
GROUP BY e.employee_name
ORDER BY total_revenue DESC;


-- 5. REVENUE BY CITY
-- Revenue by customer city

SELECT
    c.city,
    SUM(oi.quantity * oi.unit_price) AS total_revenue
FROM customers AS c
JOIN orders AS o
    ON c.customer_id = o.customer_id
JOIN order_items AS oi
    ON o.order_id = oi.order_id
WHERE o.order_status = 'Completed'
GROUP BY c.city
ORDER BY total_revenue DESC;


-- 6. CUSTOMER REVENUE
-- Highest-value customers

SELECT
    c.customer_name,
    SUM(oi.quantity * oi.unit_price) AS total_revenue
FROM customers AS c
JOIN orders AS o
    ON c.customer_id = o.customer_id
JOIN order_items AS oi
    ON o.order_id = oi.order_id
WHERE o.order_status = 'Completed'
GROUP BY c.customer_name
ORDER BY total_revenue DESC;


-- 7. ORDER STATUS ANALYSIS
-- Number of completed and cancelled orders

SELECT
    order_status,
    COUNT(order_id) AS order_count
FROM orders
GROUP BY order_status;


-- 8. AVERAGE ORDER VALUE (AOV)
-- Average revenue per completed order

SELECT
    AVG(order_revenue) AS average_order_value
FROM (
    SELECT
        o.order_id,
        SUM(oi.quantity * oi.unit_price) AS order_revenue
    FROM orders AS o
    JOIN order_items AS oi
        ON o.order_id = oi.order_id
    WHERE o.order_status = 'Completed'
    GROUP BY o.order_id
) AS order_totals;


-- 9. REVENUE BY DEPARTMENT
-- Revenue generated by each employee department

SELECT
    e.department,
    SUM(oi.quantity * oi.unit_price) AS total_revenue
FROM employees AS e
JOIN orders AS o
    ON e.employee_id = o.employee_id
JOIN order_items AS oi
    ON o.order_id = oi.order_id
WHERE o.order_status = 'Completed'
GROUP BY e.department
ORDER BY total_revenue DESC;


-- 10. TOP 5 ORDERS
-- Five highest-value completed orders

SELECT
    o.order_id,
    o.order_date,
    c.customer_name,
    SUM(oi.quantity * oi.unit_price) AS order_revenue
FROM orders AS o
JOIN customers AS c
    ON o.customer_id = c.customer_id
JOIN order_items AS oi
    ON o.order_id = oi.order_id
WHERE o.order_status = 'Completed'
GROUP BY
    o.order_id,
    o.order_date,
    c.customer_name
ORDER BY order_revenue DESC
LIMIT 5;